drop table if exists admins CASCADE;
drop table if exists calendars CASCADE;
drop table if exists companies CASCADE;
drop table if exists company_employees CASCADE;
drop table if exists company_leaders CASCADE;
drop table if exists company_types CASCADE;
drop table if exists customers CASCADE;
drop table if exists emails CASCADE;
drop table if exists events CASCADE;
drop table if exists files CASCADE;
drop table if exists interpreters CASCADE;
drop table if exists locations CASCADE;
drop table if exists login_attempts CASCADE;
drop table if exists price_patterns CASCADE;
drop table if exists price_pattern_price_mapping CASCADE;
drop table if exists roles CASCADE;
drop table if exists switching_call_center_employees CASCADE;
drop table if exists switching_call_center_leaders CASCADE;
drop table if exists switching_centers CASCADE;
drop table if exists timesheets CASCADE;
drop table if exists translators CASCADE;
drop table if exists user_news CASCADE;
drop table if exists users CASCADE;
create table admins (sms_certification boolean not null, user_id bigint not null, primary key (user_id));
create table calendars (id bigint not null, name varchar(255) not null, title varchar(255) not null, user_id bigint, primary key (id));
create table customers (sms_certification boolean, credit_private numeric(19,2) not null, credit_working numeric(19,2), user_id bigint not null, primary key (user_id));
create table emails (id bigint not null, email varchar(255) not null, name varchar(255) not null, title varchar(255) not null, user_id bigint, primary key (id));
create table events (id bigint not null, content varchar(512), description varchar(256), duration integer not null, event_type varchar(255) not null, name varchar(64) not null, primary key (id));
create table files (id bigint not null, data blob, file_type varchar(255), name varchar(255), primary key (id));
create table interpreters (bank_data varchar(255) not null, bank_details varchar(255) not null, certificate boolean not null, link_for_videocall varchar(255) not null, location_online varchar(2000) not null, payment_interval varchar(2000) not null, topic_knowledge varchar(2000) not null, user_id bigint not null, primary key (user_id));
create table locations (id bigint not null, city varchar(64) not null, country varchar(64) not null, description varchar(128), location_name varchar(64) not null, postal_code varchar(16) not null, street varchar(64) not null, primary key (id));
create table login_attempts (user_id bigint not null, blocked boolean, attempts integer, primary key (user_id));
create table price_patterns (id bigint not null, name varchar(255), primary key (id));
create table price_pattern_price_mapping (price_pattern_id bigint not null, price_mapping double, price_mapping_key integer not null, primary key (price_pattern_id, price_mapping_key));
create table roles (id bigint not null, name varchar(255) not null, primary key (id));
create table companies (invoice varchar(255), link_for_video_call varchar(255) not null, name varchar(255) not null, url varchar(255) not null, user_id bigint not null, primary key (user_id));
create table company_employees (company_employee_link_for_video_call varchar(255), user_id bigint not null, company_user_id bigint not null, primary key (user_id));
create table company_leaders (company_leader_link_for_video_call varchar(255), user_id bigint not null, company_user_id bigint not null, primary key (user_id));
create table company_types (id bigint not null, name varchar(255) not null, primary key (id));
create table switching_call_center_employees (employee_link_for_video_call varchar(255), user_id bigint not null, switching_call_center_user_id bigint not null, primary key (user_id));
create table switching_call_center_leaders (leader_link_for_video_call varchar(255), user_id bigint not null, switching_call_center_user_id bigint not null, primary key (user_id));
create table switching_centers (link_for_video_call varchar(255) not null, name varchar(255) not null, url varchar(255) not null, user_id bigint not null, primary key (user_id));
create table timesheets (id bigint not null, name varchar(255) not null, sheet varchar(255) not null, user_id bigint, primary key (id));
create table translators (sms_certification boolean, bank_data varchar(255), certification boolean, link_for_video_call varchar(255), location_online varchar(2000), payment_interval varchar(2000), topic_knowledge varchar(2000), user_id bigint not null, primary key (user_id));
create table user_news (id bigint not null, news_id bigint, user_id bigint, primary key (id));
create table users (user_id bigint not null, birthday timestamp, counter time, country varchar(255), first_name varchar(255), last_name varchar(255), house_no varchar(255), last_login timestamp, location varchar(255), online_status boolean, password varchar(255) not null, pdfs varchar(2000), phone_no varchar(255), profile_photo varchar(255), street varchar(255), user_since timestamp, user_type varchar(255), username varchar(255) not null, zip integer, role_id bigint, primary key (user_id));
alter table admins add constraint UK_h0s6b5xc1rlsc7haf8jfiurtq unique (sms_certification);
alter table calendars add constraint UK_6li3adlkeys9uil7kw5weqssi unique (name);
alter table calendars add constraint UK_cadkbs2hxnly4p20b49ajs171 unique (title);
alter table emails add constraint UK_1u6nfbte7kqw4vwsaw6pq0qyh unique (email);
alter table emails add constraint UK_ossn2iijpjf5nwq9dlr6fe4lo unique (name);
alter table emails add constraint UK_6486qqcb3daye6kg3mjas992a unique (title);
alter table interpreters add constraint UK_nv5q0hxb7jes3wy0bqllg6up5 unique (bank_details);
alter table interpreters add constraint UK_fn9f1mq8gqv7kh3dl7fi7dy9k unique (location_online);
alter table interpreters add constraint UK_iwcgxtjprqy3jyn1yfa0egskt unique (topic_knowledge);
alter table roles add constraint UK_ofx66keruapi6vyqpv6f2or37 unique (name);
alter table timesheets add constraint UK_ms1iycfl108swuvt3b5qhemrn unique (name);
alter table timesheets add constraint UK_d3mceaixvfd17dkgaypy0bkga unique (sheet);
alter table admins add constraint FKgc8dtql9mkq268detxiox7fpm foreign key (user_id) references users;
alter table calendars add constraint FK2ef443fpfyuaay9nc09tvhjre foreign key (user_id) references users;
alter table customers add constraint FKrh1g1a20omjmn6kurd35o3eit foreign key (user_id) references users;
alter table emails add constraint FK41wb6kvdemvj1602iltrfr1uo foreign key (user_id) references users;
alter table interpreters add constraint FK27ebfyeidbuyc754mqaxphrmq foreign key (user_id) references users;
alter table login_attempts add constraint FKtg9vhke4mlf5vij2rcvfk2dg2 foreign key (user_id) references users;
alter table price_pattern_price_mapping add constraint FKrocdjwj3olkmw8fkeq8fuac1l foreign key (price_pattern_id) references price_patterns;
alter table companies add constraint FK9l5d0fem75e59uwf9upwuf9du foreign key (user_id) references users;
alter table company_employees add constraint FK2ohj0sley2kkmib7ompmxeyqy foreign key (company_user_id) references companies;
alter table company_employees add constraint FKrecqd5qv28wi34imcq6x201v5 foreign key (user_id) references users;
alter table company_leaders add constraint FKm9kc2pl5dxv71n69itbdvrq1s foreign key (company_user_id) references companies;
alter table company_leaders add constraint FKdomivt7q67x79gmnkl09vhxam foreign key (user_id) references users;
alter table switching_call_center_employees add constraint FK3aqq6l73n1rvcav4q8r76sci5 foreign key (switching_call_center_user_id) references switching_centers;
alter table switching_call_center_employees add constraint FKk27fe2j85q356jq4f1un81vag foreign key (user_id) references users;
alter table switching_call_center_leaders add constraint FKi4p52demibpd7nren7v9m2t5g foreign key (switching_call_center_user_id) references switching_centers;
alter table switching_call_center_leaders add constraint FK5o4pp8yxij2gqhvhjt2oakua4 foreign key (user_id) references users;
alter table timesheets add constraint FK2tred3eu9w7b1orap81htsr1t foreign key (user_id) references users;
alter table translators add constraint FK58vb95p3y56liq0a8xqm7guxn foreign key (user_id) references users;
alter table users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);
alter table users add constraint FKp56c1712k691lhsyewcssf40f foreign key (role_id) references roles;

